# Application baseline configuration
spring.application.name=mini-core-bank

# Datasource config
spring.datasource.url=${BANK_DB_URL:jdbc:postgresql://localhost:5432/mini_core_bank}
spring.datasource.username=${BANK_DB_USERNAME:mini_core_bank}
spring.datasource.password=${BANK_DB_PASSWORD:mini_core_bank}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway migration configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.encoding=UTF-8
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true

# JDBC pool baseline
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.pool-name=MiniCoreBankHikariPool

# Logging levels
logging.level.org.flywaydb=INFO
logging.level.org.springframework.jdbc.core=INFO