package com.moesegfault.banking.presentation.gui.investment;

import com.moesegfault.banking.application.investment.result.InvestmentProductResult;
import com.moesegfault.banking.presentation.gui.mvc.AbstractGuiModel;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * @brief 创建投资产品页面模型（Create Product Page Model）；
 *        GUI model holding create-product form state and operation feedback.
 */
public final class CreateProductModel extends AbstractGuiModel {

    /**
     * @brief 表单字段快照（Form Field Snapshot）；
     *        Form field values keyed by unified schema names.
     */
    private final Map<String, String> formValues = new LinkedHashMap<>();

    /**
     * @brief 提交中标记（Submitting Flag）；
     *        Whether current request is being submitted.
     */
    private boolean submitting;

    /**
     * @brief 错误消息（可空）（Error Message, Nullable）；
     *        Error message when command handling fails.
     */
    private String errorMessageOrNull;

    /**
     * @brief 成功消息（可空）（Success Message, Nullable）；
     *        Success message when command handling succeeds.
     */
    private String successMessageOrNull;

    /**
     * @brief 最近创建结果（可空）（Latest Created Result, Nullable）；
     *        Latest investment-product result for read-back display.
     */
    private InvestmentProductResult latestResultOrNull;

    /**
     * @brief 构造模型并初始化默认字段（Construct Model with Default Fields）；
     *        Construct model and initialize default form values.
     */
    public CreateProductModel() {
        formValues.put(InvestmentGuiSchema.FIELD_PRODUCT_TYPE, "FUND");
        formValues.put(InvestmentGuiSchema.FIELD_CURRENCY_CODE, "CNY");
        formValues.put(InvestmentGuiSchema.FIELD_RISK_LEVEL, "R1");
    }

    /**
     * @brief 读取表单字段（Read Form Values）；
     *        Read immutable snapshot of current form values.
     *
     * @return 表单字段映射（Form-value map snapshot）。
     */
    public Map<String, String> formValues() {
        return Map.copyOf(formValues);
    }

    /**
     * @brief 批量更新表单字段（Update Form Values In Batch）；
     *        Update form values by replacing keys present in given map.
     *
     * @param values 字段映射（Field-value map）。
     */
    public void updateFormValues(final Map<String, String> values) {
        final Map<String, String> normalizedValues = Objects.requireNonNull(values, "values must not be null");
        normalizedValues.forEach((fieldName, fieldValue) -> {
            final String normalizedFieldName = Objects.requireNonNull(fieldName, "fieldName must not be null");
            formValues.put(normalizedFieldName, fieldValue == null ? "" : fieldValue);
        });
        fireChanged("formValues");
    }

    /**
     * @brief 读取提交中标记（Read Submitting Flag）；
     *        Read whether command submission is in progress.
     *
     * @return 提交中返回 true（true when submitting）。
     */
    public boolean submitting() {
        return submitting;
    }

    /**
     * @brief 读取错误消息（可空）（Read Error Message, Nullable）；
     *        Read error message generated by last failed submission.
     *
     * @return 错误消息或 null（Error message or null）。
     */
    public String errorMessageOrNull() {
        return errorMessageOrNull;
    }

    /**
     * @brief 读取成功消息（可空）（Read Success Message, Nullable）；
     *        Read success message generated by last successful submission.
     *
     * @return 成功消息或 null（Success message or null）。
     */
    public String successMessageOrNull() {
        return successMessageOrNull;
    }

    /**
     * @brief 读取最近结果（可空）（Read Latest Result, Nullable）；
     *        Read latest created product result.
     *
     * @return 产品结果或 null（Product result or null）。
     */
    public InvestmentProductResult latestResultOrNull() {
        return latestResultOrNull;
    }

    /**
     * @brief 标记开始提交（Mark Submission Started）；
     *        Mark model state entering submission phase.
     */
    public void markSubmitting() {
        this.submitting = true;
        this.errorMessageOrNull = null;
        this.successMessageOrNull = null;
        fireChanged("submitting", "errorMessageOrNull", "successMessageOrNull");
    }

    /**
     * @brief 标记提交成功（Mark Submission Succeeded）；
     *        Mark model state after successful create command.
     *
     * @param result 结果对象（Create-product result）。
     * @param successMessage 成功消息（Success message）。
     */
    public void markSuccess(final InvestmentProductResult result, final String successMessage) {
        this.submitting = false;
        this.latestResultOrNull = Objects.requireNonNull(result, "result must not be null");
        this.errorMessageOrNull = null;
        this.successMessageOrNull = Objects.requireNonNull(successMessage, "successMessage must not be null");
        fireChanged("submitting", "latestResultOrNull", "errorMessageOrNull", "successMessageOrNull");
    }

    /**
     * @brief 标记提交失败（Mark Submission Failed）；
     *        Mark model state after failed create command.
     *
     * @param errorMessage 错误消息（Error message）。
     */
    public void markFailure(final String errorMessage) {
        this.submitting = false;
        this.errorMessageOrNull = Objects.requireNonNull(errorMessage, "errorMessage must not be null");
        this.successMessageOrNull = null;
        fireChanged("submitting", "errorMessageOrNull", "successMessageOrNull");
    }
}
